// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD834RHyXE6v63XH6AxrfWXrvrn3p2TFBg',
    appId: '1:479077859255:web:286caaee5b92b08563b232',
    messagingSenderId: '479077859255',
    projectId: 'kpms-3bfd3',
    authDomain: 'kpms-3bfd3.firebaseapp.com',
    storageBucket: 'kpms-3bfd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkxuzr7F08nUy8lsT4xfKdhjaqgfCdggs',
    appId: '1:479077859255:android:09d454d28f2da64563b232',
    messagingSenderId: '479077859255',
    projectId: 'kpms-3bfd3',
    storageBucket: 'kpms-3bfd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc0GqvQtkC3KOPUCWR8CLqe9aeo98z3EQ',
    appId: '1:479077859255:ios:c3f4a3f39ae7cc5363b232',
    messagingSenderId: '479077859255',
    projectId: 'kpms-3bfd3',
    storageBucket: 'kpms-3bfd3.appspot.com',
    iosBundleId: 'com.example.kpms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc0GqvQtkC3KOPUCWR8CLqe9aeo98z3EQ',
    appId: '1:479077859255:ios:c3f4a3f39ae7cc5363b232',
    messagingSenderId: '479077859255',
    projectId: 'kpms-3bfd3',
    storageBucket: 'kpms-3bfd3.appspot.com',
    iosBundleId: 'com.example.kpms',
  );
}
